name: Hugo deploy to repo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.71.0
          TARGET_REPO: nihalmm/nihalmm.github.io
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          HUGO_EXTENDED: true
          CNAME: paviraghunathan.com
