name: Hugo deploy to repo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: jsumners/gh-action-hugo-deploy@v1.0.0
        with:
          destination_repo: nihalMM/nihalmm.github.io
          destination_token: ${{ secrets.Deploy_Token }}

